trigger: none

stages:
- stage: Get main branch commits
  jobs:
  - job: get_commits
    displayName: Get commits for main branch
    pool:
        vmImage: ubuntu-20.04
    steps:
    - task: CmdLine@2
      inputs:
        script: python3 -m pip install -r etc/release_requirements.txt
    - task: PythonScript@0
      inputs:
        scriptSource: filePath
        scriptPath: scripts/get_commits.py
    - task: PublishPipelineArtifact@0
        inputs:
        artifactName: versions.yaml
        targetPath: versions.yaml

#- stage: Perform nightly tests

- stage: Create release commits
  jobs:
  - job: make_release_tags
    displayName: Create release tags
    steps:
    - task: Bash@3
      inputs:
        targetType: 'filePath'
        filePath: scripts/make_release_commits.sh
    - task: PublishPipelineArtifact@0
        inputs:
        artifactName: sdist
        targetPath: sdist

- stage: Verify distibutables
- stage: Publish distributables
