trigger: none
parameters:
- name: dry_run
  type: boolean
  default: true


stages:
- stage:
  displayName: Get main branch commits
  jobs:
  - template: jobs/release/get-commits.yml

#- stage: Perform nightly tests

- stage:
  displayName: Create release commits
  jobs:
  - template: jobs/release/create-release-commits.yml
    parameters:
      dry_run: ${{ parameters.dry_run }}

- stage:
  displayName: Verify distibutables
  jobs:
  - template: jobs/release/verify.yml

#- stage: Build wheels

#- stage: Publish distributables
