parameters:
- name: pools
  type: object
  default: [ "windows-2019", "macos-10.15" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Build wheels on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    steps:
    - template: setup-host.yml
    - task: DownloadPipelineArtifact@2
      displayName: Download sdist packages
      inputs:
        artifactName: sdist
        targetPath: sdist
    - ${{ if contains(pool, 'windows') }}:
      - task: BatchScript@1
        displayName: Call vcvars64.bat
        inputs:
          filename: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
          modifyEnvironment: true
    - task: Bash@3
      displayName: Prepare venv
      inputs:
        targetType: filePath
        filePath: scripts/prepare_venv_from_sdist.sh
        arguments: python sdist angr_venv
    - task: Bash@3
      displayName: Build wheels
      inputs:
        targetType: filePath
        filenPath: scripts/build_wheels.sh
    - task: PublishPipelineArtifact@1
      displayName: Publish wheel artifact
      inputs:
        artifactName: wheels-${{ pool }}
        targetPath: wheels
