parameters:
- name: dry_run
  type: boolean
  default: true

jobs:
- job: make_release_tags
  displayName: Create release tags
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml

  - task: DownloadPipelineArtifact@2
    displayName: Download versions.yml
    inputs:
      artifactName: versions.yml
      targetPath: .

  - task: PythonScript@0
    displayName: Checkout release commits
    inputs:
      scriptSource: filePath
      scriptPath: scripts/checkout_all.py
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}

  - bash: scripts/make_release_commits.sh
    displayName: Make release commits

  - bash: scripts/build_api_docs.sh
    displayName: Build API docs

  - bash: scripts/push_commits.sh
    displayName: Push commits to github
    condition: eq(${{ parameters.dry_run }}, false)

  - bash: scripts/create_sdist.sh
    displayName: Create sdists

  - task: PublishPipelineArtifact@1
    displayName: Publish sdist pacakges
    inputs:
      artifactName: sdist
      targetPath: sdist

  - task: PublishPipelineArtifact@1
    displayName: Publish API docs artifact
    inputs:
      artifactName: apidocs
      targetPath: repos/angr.github.io/api-doc
