parameters:
- name: dry_run
  type: boolean
  default: true

jobs:
- job: make_release_tags
  displayName: Create release tags
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml
  - task: DownloadPipelineArtifact@2
    displayName: Download versions.yml
    inputs:
      artifactName: versions.yml
      targetPath: .
  - task: PythonScript@0
    displayName: Checkout release commits
    inputs:
      scriptSource: filePath
      scriptPath: scripts/checkout_all.py
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}
  - task: Bash@3
    displayName: Make release commits
    inputs:
      targetType: 'filePath'
      filePath: scripts/make_release_commits.sh
  - task: Bash@3
    displayName: Push commits to github
    condition: eq(${{ parameters.dry_run }}, false)
    inputs:
      targetType: 'filePath'
      filePath: scripts/push_commits.sh
  - task: Bash@3
    displayName: Create sdists
    inputs:
      targetType: 'filePath'
      filePath: scripts/create_sdist.sh
  - task: PublishPipelineArtifact@1
    displayName: Publish sdist pacakges
    inputs:
      artifactName: sdist
      targetPath: sdist
