parameters:
- name: dry_run
  type: boolean
  default: true

jobs:
- job: make_release_tags
  displayName: Create release tags
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml
    parameters:
      git: true

  - task: DownloadPipelineArtifact@2
    displayName: Download versions.yml
    inputs:
      artifactName: versions.yml
      targetPath: .

  - task: PythonScript@0
    displayName: Checkout pre-release commits
    inputs:
      scriptSource: filePath
      scriptPath: scripts/checkout_all.py

  - bash: scripts/make_release_commits.sh
    displayName: Make release commits
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}

  - bash: scripts/get_release_versions.sh
    displayName: Get release commit hashes

  - task: PublishPipelineArtifact@1
    displayName: Publish release.yml
    inputs:
      artifactName: release.yml
      targetPath: release.yml

  - bash: scripts/create_sdist.sh
    displayName: Create sdists

  - task: PublishPipelineArtifact@1
    displayName: Publish sdist pacakges
    inputs:
      artifactName: sdist
      targetPath: sdist
