jobs:
- job: get_commits
  displayName: Get commits for main branch
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml

  - task: PythonScript@0
    displayName: Get latest commits
    inputs:
      scriptSource: filePath
      scriptPath: scripts/get_commits.py

  - task: PublishPipelineArtifact@1
    displayName: Publish versions.yml
    inputs:
      artifactName: versions.yml
      targetPath: versions.yml
