jobs:
- job: get_commits
  displayName: Get commits for main branch
  pool:
    vmImage: ubuntu-20.04
  steps:
  - task: CmdLine@2
    inputs:
      script: python3 -m pip install -r etc/release_requirements.txt
  - task: PythonScript@0
    inputs:
      scriptSource: filePath
      scriptPath: scripts/get_commits.py
  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: versions.yaml
      targetPath: versions.yaml
