parameters:
- name: dry_run
  type: boolean
  default: true

jobs:
- job:
  displayName: Publish docs
  pool:
    vmImage: ubuntu-20.04
  steps:
  - template: setup-host.yml
    parameters:
      git: true

  - task: DownloadPipelineArtifact@2
    displayName: Download versions.yml
    inputs:
      artifactName: release.yml
      targetPath: .

  - template: prepare-venv-from-artifact.yml
    parameters:
      artifact: sdist

  - bash: scripts/build_api_docs.sh
    displayName: Build API docs
    env:
      DRY_RUN: ${{ lower(parameters.dry_run) }}

  - task: PublishPipelineArtifact@1
    displayName: Publish API docs artifact
    inputs:
      artifactName: apidocs
      targetPath: repos/angr.github.io/api-doc
