parameters:
- name: pools
  type: object
  default: [ "ubuntu-20.04", "windows-2019", "macos-10.15" ]

jobs:
- ${{ each pool in parameters.pools }}:
  - job:
    displayName: Verify on ${{ pool }}
    pool:
      vmImage: ${{ pool }}
    steps:
    - template: setup-host.yml
    - task: DownloadPipelineArtifact@2
      displayName: Download sdist packages
      inputs:
        artifactName: sdist
        targetPath: sdist
    - ${{ if contains(pool, 'windows') }}:
      - task: BatchScript@1
        displayName: Call vcvars64.bat
        inputs:
          filename: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          modifyEnvironment: true
    - task: Bash@3
      displayName: Prepare venv from sdist
      inputs:
        targetType: filePath
        filePath: scripts/prepare_venv_from_sdist.sh
        arguments: python sdist angr_venv
    - task: Bash@3
      displayName: Test angr import
      inputs:
        targetType: inline
        script: |
          source angr_venv/bin/activate || source angr_venv/Scripts/activate
          python -c "import angr; print('angr imports!')"
